### PR TITLE
Brakeman always runs on start

### PR DESCRIPTION
**Pull request by jaredmoody**
So, some years later, I still use this guard plugin, and `run_on_start: false` has never worked, so I decided to look into it today.

[This line](https://github.com/guard/guard-brakeman/blob/master/lib/guard/brakeman.rb#L53) is where the trouble is, as soon as `Brakeman::Scanner.new` is called, brakeman runs.

I worked around this by making the call to `Brakeman::Scanner.new` lazy. It seems to work for me, but I'm not sure if this is the best approach or if there's some way to pass an option to `Brakeman::Scanner.new` to not run immediately, but it doesn't look like it.

Thoughts?

### CODE REVIEW

**Comment by presidentbeef** [comment]
This isn't a bad approach, necessarily, but I have to point out `Brakeman::Scanner.new` doesn't run anything, it's the `process` call that does. You could replace

```ruby
@tracker = ::Brakeman::Scanner.new(@scanner_opts).process
```

with

```ruby
@tracker = ::Brakeman::Scanner.new(@scanner_opts).tracker
```

and move the `process` call into `run_all`. I'm relatively certain that would work just as well. But no real advantage over your approach except fewer lines of code changed.

**Comment by jaredmoody** [comment]
@presidentbeef Doh, missed that `process`, thanks for the tip

Actually though I think I was just misunderstanding the `process` output - if that's one-time setup, then `run_on_start` is working correctly and I'm not sure we want to move that to where it would be called every time a full run is made.

**Comment by presidentbeef** [comment]
That's also true. It is essentially a one-time setup and I'm not sure what the implications of running it twice would be.

**Comment by oreoshake** [comment]
I released 0.8.5 with this functionality

**Pull request merged**
